# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# Repo Action 페이지에 나타날 이름
name: Java CI with Gradle

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

env:
  RESOURCE_PATH: ./src/main/resources/application-aws.properties

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Generate Environment Variables File for Properties
      uses: microsoft/variable-substitution@v1
      with:
        files: ${{ env.RESOURCE_PATH }}
      env:
        cloud.aws.access-key : ${{ secrets.AWS_S3_ACCESS_KEY }}
        cloud.aws.secret-key : ${{ secrets.AWS_S3_SECRET_KEY }}
        cloud.aws.region.static : ${{ secrets.AWS_S3_REGION }}
        cloud.aws.s3.bucket : ${{ secrets.AWS_S3_BUCKET }}

    #빌드를 하기 위한 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #빌드를 실행
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    # 전송할 파일을 담을 디렉토리 생성
    - name: Make Directory for deliver
      run: mkdir deploy

      # Jar 파일 Copy
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/

      # script file Copy
    - name: Copy shell
      run: cp ./scripts/* ./deploy/

      # appspec.yml Copy
    - name: Copy appspec
      run: cp appspec.yml ./deploy/

      # 압축파일 형태로 전달
    - name: Make zip file
      run: zip -r -qq -j ./toksdeploy.zip ./deploy

      # S3 Bucket으로 copy
    - name: Deliver to AWS S3
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
       aws s3 cp \
       --region ap-northeast-2 \
       --acl private \
       ./toksdeploy.zip s3://toksproject/

    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
       aws deploy create-deployment \
       --application-name toks-deploy \
       --deployment-group-name toks-deploy \
       --file-exists-behavior OVERWRITE \
       --s3-location bucket=toksproject,bundleType=zip,key=toksdeploy.zip \
       --region ap-northeast-2
